### ISSUE TITLE
Move to the nursery?

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-semverver#42]
I'm a huge fan of this tool; it's something we've wanted for a very long time in the Rust ecosystem.

I'm wondering if we could go ahead and get this on the path to becoming a fully "official" tool, migrating it to https://github.com/rust-lang-nursery/ for greater visibility and maintenance help?

**Comment by aturon** [comment]
cc @nrc

**Comment by ibabushkin** [comment]
I'd love that. Actually, this was already suggested in #39, but for some reason the whole process stalled a bit (possibly because I haven't had much time to work on remaining issues). I've pinged that issue yesterday and am currently working on one of the main limitations currently.

**Comment by aturon** [comment]
Ahha, so it is.

It seems like everyone is fine with it. Let's do it! I've invited you to the nursery organization, which I think is all you need to transfer ownership.

**Comment by ibabushkin** [comment]
Alright, but what team should I move this to (none of the bunch seems to be an obvious match)? Initially `dev-tools` was being discussed, but that doesn't exist in the nursery.

It's probably also possible to just create a new team, akin to the clippy-team, but that might be suboptimal for a fairly young and small tool.

That said, thank you!

**Comment by nrc** [comment]
@ibabushkin I created a semver-owners team and added you to it, so I think we should be good to go.

**Comment by ibabushkin** [comment]
Alright, moved the repo. I'll close this issue, as #39 already tracks the next steps to be taken.
