### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by ibabushkin** [rust-lang-nursery/rust-semverver#55]
Some observations on what needs to be done to provide proper support for windows users (see #53):

* [x] AppVeyor builds
* [x] document systemwide dependencies
* [x] ~~determine and implement any changes required for the platform~~ (not needed, sans full tests)

**Comment by ibabushkin** [comment]
@nrc It seems that I cannot add appveyor integration properly, because setting up the webhook is not a feauture accesible to me. Not sure if that's intended. Another point would be where we'd want our AppVeyor CI builds to run, is there an account for the nursery to use?

**Comment by nrc** [comment]
@ibabushkin you should have the necessary privs to setup the web hook now. There is a nursery account, I think it is called rust-lang-libs (or something similar) for historic reasons. I think you should be able to set that up too, let me know if you run into any problems.

**Comment by ibabushkin** [comment]
Alright, I was able to install the webhook but found no way to access the other AppVeyor account, as I think the only option of doing that would be logging in with the corresponding credentials anyway, which I don't see documented anywhere. But I guess that this isn't exactly a pressing issue, as the CI itself works properly.
